### PR TITLE
Move leeched NPCs over to the player's new team when they change team

### LINKED ISSUE #649: Hacked spectres causing a server crash in Attrition
Hello! There seems to be a crash that occurs when spectres are hacked. Something goes wrong with their teamswitch.

The relevant log snippet would seem to be:
```

[23:29:00] [SCRIPT SV] [info] SCRIPT ERROR: [SERVER] ERROR: Squad 'player13spectreSquad' has enemies in it! 523 npc_spectre [523] doesn't like 515 npc_spectre [515]
[23:29:00] [SCRIPT SV] [info]  -> guy.SetSquad( squadName )
[23:29:00] [SCRIPT SV] [info]
CALLSTACK
*FUNCTION [SetSquad()] _utility.gnut line [3512]
*FUNCTION [NPCFollowsPlayer()] ai/_ai_utility.gnut line [82]
*FUNCTION [LeechGenericThread()] pilot/_leeching.gnut line [431]

[23:29:00] [SCRIPT SV] [info] LOCALS
[squadName] "player13spectreSquad"
[guy] ENTITY (npc_spectre [523] (NPC "npc_spectre" at <-442.471 -422.705 90.5699>))
[this] TABLE
[squadName] "player13spectreSquad"
[leader] ENTITY (player J4GE [13] (player "J4GE" at <-425.756 -397.111 90.5699>))
[npc] ENTITY (npc_spectre [523] (NPC "npc_spectre" at <-442.471 -422.705 90.5699>))
[this] TABLE
[timerCredit] 9
[leechSound] "diag_spectre_gs_LeechEnd_01_1"
[leecher] ENTITY (player J4GE [13] (player "J4GE" at <-425.756 -397.111 90.5699>))
[self] ENTITY (npc_spectre [523] (NPC "npc_spectre" at <-442.471 -422.705 90.5699>))
[this] TABLE

DIAGPRINTS
```

### PR DESCRIPTION
**Pull request by ASpoonPlaysGames**
closes #649 (the other part of that should be fixed already by other changes)

side note: i have no idea what happened to the commit history here wtf?

### CODE REVIEW

**Comment by GeckoEidechse** [comment]
"Leeched NPCs" are things like hacked Spectres, right?

**Comment by ASpoonPlaysGames** [comment]
> "Leeched NPCs" are things like hacked Spectres, right?

yeah

**Comment by EM4Volts** [comment]
tested ingame, works. 
spawned a hacked spectre, switched team, spectre switched over with me.

**Review by Alystrasz — APPROVED** [review]
Leeched NPCs don't attack master player anymore after they swapped teams.

Command used to create and attach a spectre: `ent_create npc_spectre; script DoLeech(GetNPCArrayByClass("npc_spectre")[0], GetPlayerArray()[0])`

**Comment by Zanieon** [comment]
This should be closed as #789 was merged and serves the same purpose.

**Pull request closed without merging**
