### PR TITLE
Fix connecting UI

### PR DESCRIPTION
**Pull request by F1F7Y**
Hi @GeckoEidechse :)

The #553 PR accidentally moved the circle animation and the button. This PR fixes their alignment.

### CODE REVIEW

**Comment by GeckoEidechse** [comment]
Just so I can verify, what am I looking for exactly? ^^
(screenshot would be appreciated <3)

**Comment by F1F7Y** [comment]
> Current main
image

> This PR
image

**Review by uniboi — APPROVED** [review]
has original coordinates again

**Review by GeckoEidechse — APPROVED** [review]
Issue confirmed in main and confirmed resolved in testing.

**Pull request merged**
