### PR TITLE
Merge attrition into main

### PR DESCRIPTION
**Pull request by F1F7Y**
**Northstar.Client**
- Adds archer grunts playlist var localization
- Unlocks Attrition in the private match mode select menu

**Northstar.Custom**
- Fixes AI 1st person execution crash

**Northstar.CustomServers**
- Adds Attrition
- Bounty hunt leftovers

### CODE REVIEW

**Comment by F1F7Y** [comment]
why did it create a pr without asking me what o put into the title and description

**Comment by BobTheBob9** [comment]
we should probably make sure that bounty hunt is disabled for now before merging this

**Comment by F1F7Y** [comment]
I only unlocked attrition so unless you're a modder, or someone told you how, you won't be able to start bounty hunt. Unless you're talking about dedi, in which case I wouldn't touch it and let ppl host whatever they want

**Comment by GeckoEidechse** [comment]
> Unless you're talking about dedi, in which case I wouldn't touch it and let ppl host whatever they want

Not sure how we do it now but basically we should just make sure we don't accidentally incentivise server hosters to host unfinished _Bounty Hunt_ ^^

**Comment by F1F7Y** [comment]
uhhhh

**Comment by F1F7Y** [comment]
right now either you select the gamemode in the mode select menu, or you put `+mp_gamemode aitdm` into launch args

theoratically you could launch bounty hunt with `+mp_gamemode at`, but it's always been like this

**Comment by GeckoEidechse** [comment]
> theoratically you could launch bounty hunt with `+mp_gamemode at`, but it's always been like this

Yeah that's perfectly fine if it stays as is in that regard ^^

**Comment by GeckoEidechse** [comment]
Tested in public matches with playtesters, seems to work good enough <3

**Pull request merged**
