### PR TITLE
Improvements to The Hidden

### PR DESCRIPTION
**Pull request by iCrazyBlaze**
The Hidden is given a kunai melee. Some other code cleanup

The Kunai is much more fun to use as a melee and fits well with The Hidden

### CODE REVIEW

**Comment by iCrazyBlaze** [comment]
For more balancing changes, I'm thinking of cooldown for the survivor arc grenades as someone in a server just mentioned, writing it here so i don't forget

**Comment by x3Karma** [comment]
Eh, yet another conflicting idea.

I've been playing the hidden for 2 days on my server and yet it's pretty 50/50 whether you get a good Hidden or someone who just gets killed instantly by arc nades and Kraber.

I had another buff idea which is to give the Hidden more air acceleration, simply because you can't really keep track of him if he moves fast even if he does flicker.

But I'd say this should be fine to be merged and see how it goes lol

**Review by x3Karma — COMMENTED** [review]
You added a new arc nade mod but you forgot to apply it

**Comment by x3Karma** [comment]
Err 11 days now still no changes lmao

**Pull request closed without merging**
