### PR TITLE
Add much needed IsEven function

### PR DESCRIPTION
**Pull request by x3Karma**
checks if a number is even or odd.

### CODE REVIEW

**Review by ASpoonPlaysGames — CHANGES_REQUESTED** [review]
I need to check if numbers below 0 are even or not, can you add support for this?

**Comment by x3Karma** [comment]
> I need to check if numbers below 0 are even or not, can you add support for this?

already done, made it so it returns false. 😄

**Review by ScureX — APPROVED** [review]
**Very good i see no problem with this**. 
This will greatly improve our math utility and streamline modding, making it more efficient. 
While this is somewhat still work in progress considering the very few missing numbers i think this is ready to merge, as numbers are rarely higher than 100, and the significant improvements this brings to the codebase greatly outweigh this rather small issue. 
LGTM (Let Gays Try Merging)

image

**Review by NoCatt — CHANGES_REQUESTED** [review]
very cleanly written and really easy to understand I hope this will help new ppl.
I would only add one thing to the closing else statement:
instead of:
`else
		return rand() % 2 != 0
`
it would be ` else
               IsEven(n-1)== true ? return false : return true`

 this should be much more efficent and makes it a LOT easier to read and know what is going on

**Comment by NoCatt** [comment]
thanks for adding the very efficent else statement

**Comment by GeckoEidechse** [comment]
Closed for obvious reasons. No fun allowed here >:(

**Comment by BobTheBob9** [comment]
oh my god

**Comment by GeckoEidechse** [comment]
Literally 1984

**Pull request closed without merging**
