### PR TITLE
Added Sticks & Stones Configuration as Playlist Vars

### PR DESCRIPTION
**Pull request by Coopyy**
not sure why there's like no other gamemodes that use this tbh, would be great for other modes to have customization
image

### CODE REVIEW

**Review by abarichello — CHANGES_REQUESTED** [review]
You just deleted the entire english localisation file, probably due to merge conflits. Remember to update/rebase your fork branch when you create a new PR.

**Comment by abarichello** [comment]
You converted the line endings to LF on `northstar_client_localisation_english.txt`, please revert back to CRLF

**Comment by Coopyy** [comment]
fixed I think tm

**Comment by Coopyy** [comment]
fixed fr this time lol

**Comment by abarichello** [comment]
Thanks

**Pull request merged**
