### PR TITLE
Revert "Revert 'Hardpoint UI Fixes (#416)' (#618)"

### PR DESCRIPTION
**Pull request by x3Karma**
Replaced the SetPlayerNetInt inside of a player check so other entities would not trigger the crash.

Full changelogs in #416.

### CODE REVIEW

**Comment by GeckoEidechse** [comment]
For anyone reviewing the change from #416 is e5de5a6880cefde46e8fdb3adbecd3d19853a371

**Review by catornot — APPROVED** [review]
I tested this on colony and some other maps with bots and I didn't get any crashes.

**Review by F1F7Y — CHANGES_REQUESTED** [review]
Blocking untill discord conversation is resolved. ( [link](https://discord.com/channels/920776187884732556/922954389415686185/1098964549991944252) )

**Review by F1F7Y — APPROVED** [review]
Works in testing

**Review by pg9182 — APPROVED** [review]
Tested launching a few maps; everything seems to work fine.

**Pull request merged**
