### PR TITLE
Revert "improve fastball respawn logic"

### PR DESCRIPTION
**Pull request by GeckoEidechse**
Reverts 050e707f4762b976791c0934b88779e038f70ade as it caused two separate issues (#169 and #170)

### CODE REVIEW

**Comment by GeckoEidechse** [comment]
Will also undo one of the completed tasks of #132

But now we at least know that it can cause some regressions :P

**Comment by BobTheBob9** [comment]
i think this is an issue with the change to SetControlPanelUseFunc for panel hacks, i'd prefer to figure out why this is has introduced the bug rather than reverting the whole thing

**Comment by GeckoEidechse** [comment]
Usually I'd agree but as that one commit introduced two separate regressions I'd argue it makes more sense to revert it and then re-add the changes the two changes under proper testing one commit at a time.

Your call though ¯\\\_(ツ)\_/¯

**Comment by laundmo** [comment]
theres a third regression: the B spot on glitch spawns ppl in the water, instantly killing them. please revert until a solution can be found that doesnt cause these issues.

**Comment by BobTheBob9** [comment]
aight sure i'll revert for now and try to get a more robust version of these changes pushed soon

**Pull request merged**
