### PR TITLE
Set communities_hostname on main menu

### PR DESCRIPTION
**Pull request by emma-miler**
Depends on #213

### CODE REVIEW

**Comment by GeckoEidechse** [comment]
Closes #201

**Comment by GeckoEidechse** [comment]
Could you maybe open a new PR with just the that fix? ^^
(i.e. with no dependency on #213 which is why this was closed in the first place I assume)

**Comment by emma-miler** [comment]
I thought this was fixed by a different PR already? I might be wrong though.

**Comment by GeckoEidechse** [comment]
Not that I'm aware ^^

**Pull request closed without merging**
