### PR TITLE
fixing peacekraber in sp

### PR DESCRIPTION
**Pull request by catornot**
closes this issue #348

### CODE REVIEW

**Review by RoyalBlue1 — APPROVED** [review]

**Comment by GeckoEidechse** [comment]
So turns out this actually breaks SP for me :c

image

**Comment by catornot** [comment]
I will check tmr, I believe it's smth to do with coop.

**Comment by GeckoEidechse** [comment]
> I will check tmr, I believe it's coop that fixes it fully.

Hmm, I do have Coop installed (the version on `main` rn) but it was disabled. Neither enabling it, nor deleting it and restarting gave me a different result. Always the error message posted above :I

**Comment by catornot** [comment]
Ok I will see what happened.

**Comment by GeckoEidechse** [comment]
Looks like I'm not alone with this issue :/
https://discord.com/channels/920776187884732556/987319483846778890/987329756104101889

I'm probably gonna revert the change again for now, so maybe give it another shot by making a fresh fork from `main` once it's been reverted ^^

**Comment by GeckoEidechse** [comment]
Reverted in d70aaafc0ac745113cc4cb9767a3d1f847571d57

**Pull request merged**
