### PR TITLE
Added Killer Outline

### PR DESCRIPTION
**Pull request by DBmaoha**
Added killer outline: highlight the killer after being killed

### CODE REVIEW

**Comment by x3Karma** [comment]
For this PR, I think adding it to `_base_gametype_mp.gnut` is good enough.
image

Tested by adding it on line 302 of the file.

**Comment by DBmaoha** [comment]
will this be better? moved it to _base_gametype_mp.gnut

**Comment by x3Karma** [comment]
> will this be better? moved it to _base_gametype_mp.gnut

oh move it inside the `if ( IsValid ( attacker ) )` check. Also remove the `attacker.IsNPC()`, NPCs don't have outline I'm pretty sure.

**Comment by DBmaoha** [comment]
> > will this be better? moved it to _base_gametype_mp.gnut
> 
> oh move it inside the `if ( IsValid ( attacker ) )` check. Also remove the `attacker.IsNPC()`, NPCs don't have outline I'm pretty sure.
> 
> EDIT: https://www.youtube.com/watch?v=ZyBt8Jg5Vic&ab_channel=x3Karma, grunts doesn't have outline when killing a player.

got it

**Review by x3Karma — APPROVED** [review]

**Review by ASpoonPlaysGames — APPROVED** [review]

**Comment by BobTheBob9** [comment]
looks great, surprised i never saw this func

**Pull request merged**
