### PR TITLE
Funny scrollbar and dialog PR

### PR DESCRIPTION
**Pull request by VITALISED**
This PR plans to address some aged menu design, I'm making this a draft if people want to give out ideas and shape how this works or offer help, etc.

What I want to implement right now:
- Confirmation to join a server.
- Joining of buttons in Server Browser.
- (Maybe) Support to add toggleconsole bind.

If anyone has any ideas I'd like to add them too because I figure these things out as I'm working usually

### CODE REVIEW

**Comment by BobTheBob9** [comment]
atm a toggleconsole bind should already be present in autoexec_ns_client, but this could be easier to reach yeah

**Comment by VITALISED** [comment]
Didn't notice server browser buttons got joined, my bad. Also, is there any diff-ing (such as with localisations) for kb_act.lts?

**Comment by BobTheBob9** [comment]
remove the -1 [here](https://github.com/R2Northstar/NorthstarMods/pull/8/commits/0530b851ea8274d45cda2644eefe0297834d64d3#diff-265ac8842998ac03555e80996bdacf126d0717a6570c4b8d9ffb171421c66fa0R138) or server list will cut off last server
also, how does this react to failing to connect to servers?

**Comment by VITALISED** [comment]
Failed connection behavior isn't changing, just boots to frontend with the error, unless this wasn't how it was before

**Comment by BobTheBob9** [comment]
i mean specifically if you time out authenticating with a server, not actually connecting

**Comment by VITALISED** [comment]
I think any new OpenDialogs() just kill off the old one, so it shouldn't be problem

**Comment by MiloAkerman** [comment]
How about an automatic region prefix for servers based on IP geolocation?

**Comment by pg9182** [comment]
That's what I'm planning to work on in R2Northstar/Northstar#41.

**Comment by CaptainDiqhedd** [comment]
oh my god viatlised this is so cool please bob accept it right now!!!

**Comment by VITALISED** [comment]
thank you for the constructive criticism @CaptainDiqhedd, i do whole heartedly believe bobthebob9 should stop donowalling my pr and calling my scrollbar "bad" and "doesn't suit the aesthetic of the rest of the ui" (it is very good) I have since he said this adjusted the color and size and I know he reads the git discord channel more than actual mentions so he will see this and have an epiphany of "wow this scrollbar is amazing oh my god vitalised this is so cool im going to accept it right now" (which is going to happen) (tomorrow) (or maybe today)

**Comment by VITALISED** [comment]
Also this fixes weird SWITCH_ANY moment stuff (only took me 2 years to figure it out)

**Comment by F1F7Y** [comment]
Is this the funny scrollbar PR?

**Review by BobTheBob9 — CHANGES_REQUESTED** [review]
general consensus seems to be not to merge the scrollbar change, there's no need to change the current one in core mods
i'm also not sure why you've removed the preexisting "connecting" ui from the server browser
there's also no feedback on a connection failure, it'll just continue displaying the "connecting" ui indefinately after failure
other changes here are great, though, i'd suggest moving stuff like the scrollbar to a standalone mod

**Comment by VITALISED** [comment]
Did the connection stuff move to silentconnect or something? It does handle an authentication error to my knowledge and every time I've connected, it does move to the loading screen before telling me something went wrong

**Comment by BobTheBob9** [comment]
all i know is that if authentication with a server failed (i.e. pre-connection) there'd be an error log in console but no message ingame, i pulled Northstar.Client from your repo to test

**Comment by VITALISED** [comment]
I'll probably do this later I wanna work on TFFA over this tbh

**Pull request closed without merging**
