### PR TITLE
Add grunt chatter about killed squadmates

### PR DESCRIPTION
**Pull request by Zanieon**
This restores a small detail that Grunts speaks when their squadmates dies in multiplayer matches.

### CODE REVIEW

**Comment by EnderBoy9217** [comment]
I would like to add that grunts have a LOT of voice lines that could be used but aren't, maybe add to issues list?

E.G. "Hostile titan spotted, run to that building"

**Comment by Zanieon** [comment]
> I would like to add that grunts have a LOT of voice lines that could be used but aren't, maybe add to issues list?
> 
> E.G. "Hostile titan spotted, run to that building"

I'm aware of that but lots of their voicelines are restricted to the Campaign. Multiplayer can only access the ones avaliable in the grunt_chatter_mp datatable. I don't remember if the building speech is one of the avaliable ones, i haven't heard grunts use that one on vanilla, although they still flee to buildings when they see enemy titans.

**Review by ASpoonPlaysGames — CHANGES_REQUESTED** [review]
Functions for this already exist in `_grunt_chatter.gnut`, this PR should investigate why they currently do not trigger (or if they do, why they do not work)

EDIT:
Looking at the code, `_grunt_chatter.gnut` is supposedly only meant for SP usage. `_grunt_chatter_mp.gnut` exists which one can assume is meant to handle the same stuff as `_grunt_chatter.gnut` (but for MP). However, this file seems to be (mostly) unimplemented.

Ideally this file gets implemented and a PR doing so would supercede this one

**Comment by Zanieon** [comment]
I'll refactor this PR since @ASpoonPlaysGames pointed me some chatter functions that have better implementation.

**Pull request closed without merging**
