### PR TITLE
Change gun game score limit setting

### LINKED ISSUE #308: Playing Gun Game sets score limit to 28 for all subsequent matches
After a gg match, all subsequent non-round-based matches will have their score limit set to 28.

`GetRoundScoreLimit_FromPlaylist()` and e.g. `GameMode_GetScoreLimit("aitdm")` will return 28.

### PR DESCRIPTION
**Pull request by ASpoonPlaysGames**
Closes #308 

Gun game was never set up to properly use the playlistvars for setting guns, and relied on playlistvaroverrides to set the score limit, this caused the change to persist to other modes

### CODE REVIEW

**Comment by GeckoEidechse** [comment]
What's the best way to test this?

**Comment by ASpoonPlaysGames** [comment]
> What's the best way to test this?

Try and replicate the linked issue

**Review by Jan200101 — APPROVED** [review]
Tested and does what it says on the tin. Other game modes no longer experience sideeffects from gungame.

Code simply removes previous workarounds or hacks to set the score correctly that are no longer needed.

**Comment by GeckoEidechse** [comment]
Merging based on reviews.

**Pull request merged**
