### PR TITLE
Fix Arc Cannon not hurting `npc_gunship` and `npc_pilot_elite`

### PR DESCRIPTION
**Pull request by NachosChipeados**
Fixes https://github.com/R2Northstar/NorthstarMods/issues/842 . I only NOW realized i could just pr it directly lol

### CODE REVIEW

**Comment by GeckoEidechse** [comment]
cc @Dinorush @GalacticMoblin @ASpoonPlaysGames @Masterliberty @Zanieon

**Review by Zanieon — APPROVED** [review]
I'm fine with this, @NachosChipeados might wanna do another PR to also include `npc_gunship` as they are also missing from that array, and they are still a possibility for modding in the game.

**Comment by NachosChipeados** [comment]
Question: does ``npc_pilot_elite_assassin`` work? Its not derived from ``npc_pilot_elite`` or ``npc_soldier`` so theoretically the Arc Cannon wouldn't be able to hit them, but i can't get them to spawn so i can't test it

**Comment by Zanieon** [comment]
> Question: does `npc_pilot_elite_assassin` work? Its not derived from `npc_pilot_elite` or `npc_soldier` so theoretically the Arc Cannon wouldn't be able to hit them, but i can't get them to spawn so i can't test it

It works becase what you need to care in this is the BaseClass of the aisetting definition, not the name of the setting itself, `npc_pilot_elite_assassin` still uses `npc_pilot_elite` as BaseClass, so it will be counted.

**Review by Zanieon — APPROVED** [review]
Simple additions, i see that you decided to include my suggestion, so all good for me.

**Comment by GeckoEidechse** [comment]
Given the simple nature of the change I'm fine with merging it without any further testing as it can easily be reverted should something turn out to not work out as intended ^^

**Pull request merged**
