### PR TITLE
hehe minecarft1

### PR DESCRIPTION
**Pull request by ScureX**
observe exhibit No.1: the goob
image
fr tho this is epic and we should ship it like this. these  are settings. no i dont know what anything here means
image
image

observe exhibit No.2: the boing
image

My name is Walter Hartwell White. I live at 308 Negra Arroyo Lane, Albuquerque, New Mexico, 87104. This is my confession. If you're watching this tape, I'm probably dead– murdered by my brother-in-law, Hank Schrader. Hank has been building a meth empire for over a year now, and using me as his chemist. Shortly after my 50th birthday, he asked that I use my chemistry knowledge to cook methamphetamine, which he would then sell using connections that he made through his career with the DEA. I was... astounded. I... I always thought Hank was a very moral man, and I was particularly vulnerable at the time – something he knew and took advantage of. I was reeling from a cancer diagnosis that was poised to bankrupt my family. Hank took me in on a ride-along and showed me just how much money even a small meth operation could make. And I was weak. I didn't want my family to go into financial ruin, so I agreed. Hank had a partner, a businessman named Gustavo Fring. Hank sold me into servitude to this man. And when I tried to quit, Fring threatened my family. I didn't know where to turn. Eventually, Hank and Fring had a falling-out. Things escalated. Fring was able to arrange – uh, I guess... I guess you call it a "hit" – on Hank, and failed, but Hank was seriously injured. And I wound up paying his medical bills, which amounted to a little over $177,000. Upon recovery, Hank was bent on revenge. Working with a man named Hector Salamanca, he plotted to kill Fring. The bomb that he used was built by me, and he gave me no option in it. I have often contemplated suicide, but I'm a coward. I wanted to go to the police, but I was frightened. Hank had risen to become the head of the Albuquerque DEA. To keep me in line, he took my children. For three months, he kept them. My wife had no idea of my criminal activities, and was horrified to learn what I had done. I was in hell. I hated myself for what I had brought upon my family. Recently, I tried once again to quit, and in response, he gave me this. [Walt points to the bruise on his face left by Hank in "Blood Money."] I can't take this anymore. I live in fear every day that Hank will kill me, or worse, hurt my family. All I could think to do was to make this video and hope that the world will finally see this man for what he really is.

image

### CODE REVIEW

**Review by H0L0theBard — APPROVED** [review]
Will decrease the amount of support tickets received on the Northstar discord. 
Improves the aesthetic of the game. 
:trollface:

**Comment by TH3-S4LM0N** [comment]
Actually make this a launch arg

**Review by x3Karma — APPROVED** [review]

**Comment by ScureX** [comment]
Cant help em if both console and errors are unreadable

**Comment by ScureX** [comment]
@TH3-S4LM0N wouldnt that make it optional

**Comment by BBQGiraffe** [comment]
fun fact: you won't get annoying bug reports if your users can't figure out what's going on or how to submit anything 
image

**Comment by ScureX** [comment]
@TH3-S4LM0N 4:30am rn but if u show me how to do that ill make another epic gamer pr with that as arg

**Comment by TH3-S4LM0N** [comment]
Heh
Yh I got no idea either

**Comment by GeckoEidechse** [comment]
Merged #440 into main.

**Comment by x3Karma** [comment]
> Merged #440 into main.

I saw the email and got hyped for a sec

**Comment by GeckoEidechse** [comment]
> > Merged #440 into main.
> 
> I saw the email and got hyped for a sec

:trollface:

**Comment by GeckoEidechse** [comment]
Anyway I think it's clear why it's not going in. Although I wouldn't mind giving this a shot for something like April Fools ^^

**Comment by ScureX** [comment]
hey @GeckoEidechse, u stink >:(
image
image

**Comment by uniboi** [comment]
Does this PR add MSAL authentification to Northstar?

**Comment by x3Karma** [comment]
@F1F7Y @uniboi 
We need reviewers for this

**Pull request closed without merging**
