### PR TITLE
Northstar Italian translation

### PR DESCRIPTION
**Pull request by m4t7w**
Translated to Italian

### CODE REVIEW

**Review by abarichello — COMMENTED** [review]
Please fix the identation, there's a mix of space and tabs.
image
Also remove the spaces between the translation key and the translated word, there's no need to vertically align everything

**Comment by m4t7w** [comment]
Should be fixed now, i don't know how i missed that...

**Comment by abarichello** [comment]
The file isn't encoded as UTF-16 LE, lines 238 to 256 still use spaces for indentation and you missed the translation for `"no_pilot_collision"`

**Comment by abarichello** [comment]
Thanks!

**Pull request merged**
