### PR TITLE
[BH] MVP dialogue

### PR DESCRIPTION
**Pull request by ASpoonPlaysGames**
Also maybe improves the AI movement
Also fixes a small bug with audio

### CODE REVIEW

**Comment by ASpoonPlaysGames** [comment]
I can't push to bounty hunt branch myself :(

**Review by F1F7Y — APPROVED** [review]
Code looks good

**Comment by F1F7Y** [comment]
> I can't push to bounty hunt branch myself :(

@GeckoEidechse this sounds like a perms thing, mods-reviewers should be able to push to non-main branches, no?

**Comment by pg9182** [comment]
No, they aren't supposed to be able to, @F1F7Y. We could add an exception for the BH branch though.

**Pull request merged**
