### PR TITLE
北极星缺失细节修复

### PR DESCRIPTION
**Pull request by DBmaoha**
-修复了相位回溯距离错误、时间错误且结束后可能卡墙的问题
-修复了强化武器多次使用后会出现计时器错误且第一次使用后30s会结束所有强化武器的问题
-修复了无运输船开局的回合制模式开局倒数时可能可以自由移动的问题
-修改了回合或游戏结束后的视觉效果，添加了战斗对话及音乐，更贴近官服
-修复了死亡后超量泰坦值不重置的问题
-修复了作为泰坦复活后立刻摧毁泰坦，在拥有一定超量泰坦值的情况下可以再次获取一台泰坦的问题
-修复了经典驯牛术和留学倒地的崩溃及视听问题，修复了撤离阶段的视听效果

### CODE REVIEW

**Comment by BobTheBob9** [comment]
cool

**Comment by DBmaoha** [comment]
> cool

hmmmm I was going to make a pull request to NorthstarCN and I'm to stupid to do that :(

**Comment by p0358** [comment]
For a second I thought it's https://github.com/R2Northstar/NorthstarLauncher/pull/57 all over again xd

**Comment by p0358** [comment]
> hmmmm I was going to make a pull request to NorthstarCN and I'm to stupid to do that :(

I think you need to go on their repo and click `New pull request` there, and select correct branches

**Pull request closed without merging**
