### PR TITLE
Fixed Turret Visual

### PR DESCRIPTION
**Pull request by DBmaoha**
Run _ai_turret_sentry.gnut on ServerSide so that turret will spawn with it's laser

### CODE REVIEW

**Review by x3Karma — APPROVED** [review]

**Comment by x3Karma** [comment]
not sure why _ai_turret_sentry.gnut wasn't loaded at all, either a file name issue or we just didn't load it in mod.json.

**Comment by DBmaoha** [comment]
frontend.vpk's scripts.rson only runs _ai_turret_sentry.gnut on SERVER && SP, I think this is the reason

**Review by GeckoEidechse — APPROVED** [review]
Works when tested with pilot sentry. Pre-patch has has the laserbeam missing, post-patch has it.

**Comment by GeckoEidechse** [comment]
I'm curious though why that file was not included previously...

@BobTheBob9 any specific reason or just oversight? ^^

**Comment by BobTheBob9** [comment]
> I'm curious though why that file was not included previously...
> 
> @BobTheBob9 any specific reason or just oversight? ^^

weird, if vanilla needs it then vanilla should include it, same with all other server scripts

**Comment by BobTheBob9** [comment]
just to make sure, we are sure this laser is supposed to appear in mp right? if it isn't included in scripts.rson then vanilla servers don't run it

**Comment by GeckoEidechse** [comment]
So it does have a laser on vanilla

mp_forwardbase_kodai0005

**Pull request merged**
