### PR TITLE
Fixed EarnMeter OverDrive not reset after player died

### PR DESCRIPTION
**Pull request by DBmaoha**
Earn meter Overdrive( yellow bar ) will be reset to 0 after player died

### CODE REVIEW

**Comment by x3Karma** [comment]
Does this fix the bug where you can immediately call another Titan after your first Titan died?

**Comment by DBmaoha** [comment]
> Does this fix the bug where you can immediately call another Titan after your first Titan died?

don't know, how that bug work?

**Comment by ASpoonPlaysGames** [comment]
> > Does this fix the bug where you can immediately call another Titan after your first Titan died?
> 
> don't know, how that bug work?

we dont really know, but if a player somehow gained 100% overdrive meter while in their titan and it never got removed then they would get their titan immediately on respawn probably?

**Comment by DBmaoha** [comment]
> > > Does this fix the bug where you can immediately call another Titan after your first Titan died?
> > 
> > 
> > don't know, how that bug work?
> 
> we dont really know, but if a player somehow gained 100% overdrive meter while in their titan and it never got removed then they would get their titan immediately on respawn probably?

what if we reset overdrive after they disembark?
maybe this will fix it too, never met that bug before

**Review by ASpoonPlaysGames — APPROVED** [review]
Provided that this case doesnt happen, i think this is good.

Player has 70% meter + 30% overdrive
Player therefore can call titan
Player dies
Player loses 30% overdrive
Player can no longer call titan

(If this does happen, the fix would be to just set the owned frac to 100% as soon as the player can call their titan, wherever that function is)

**Comment by DBmaoha** [comment]
> > > Does this fix the bug where you can immediately call another Titan after your first Titan died?
> > 
> > 
> > don't know, how that bug work?
> 
> we dont really know, but if a player somehow gained 100% overdrive meter while in their titan and it never got removed then they would get their titan immediately on respawn probably?

I've done this fix in another branch that I haven't created a pr, I tried "ClearTitanAvaliable()" after "RespawnAsTitan()" is triggered and it gets fixed

**Pull request merged**
