### PR TITLE
Swap EVAC_WAIT_TIME to waitTime in _evac.gnut

### PR DESCRIPTION
**Pull request by x3Karma**
- Use the variable `waitTime` instead of the const `EVAC_WAIT_TIME`,

### CODE REVIEW

**Review by ASpoonPlaysGames — APPROVED** [review]
Don't know why we aren't already doing this, approving assuming that we are passing EVAC_WAIT_TIME to waitTime when needed

**Comment by x3Karma** [comment]
yeah its just a small slip-up, this PR will prevent players from seeing 18 seconds timer on the dropship even if a custom `waitTime` is set.

**Review by BobTheBob9 — APPROVED** [review]
yeah seems to have been a typo, looks great

**Comment by ASpoonPlaysGames** [comment]
PR speedrun any%

**Comment by x3Karma** [comment]
> PR speedrun any%

real

**Pull request merged**
