### PR TITLE
Update tbshotgun mdls with skinfamillies/lods, add pbr materials

### PR DESCRIPTION
**Pull request by CozyMerc**
- Both `ptpov` and `w_` models now have proper skinfamillies resembling average r2 weapon setup (default/skin31/prime 0-6)
- added `lod0`-`lod3` models to the `w_` model
- removed references textures and models referencing weapons which were used as base for tb.
- rpak is now only `1024x` for tb, shell is `512x`.
- rpak now fully supports r2 pbr
- rpak now contains newly created skin31 material + dummy materials for prime skins 1-6 to prevent missing texture issues
- Replaced missing audio events with already existing sounds:
```
	format
	{old event}
	{new event}
	open
	{ event AE_CL_PLAYSOUND 4 "SG_Twin_B.Reload_Open" } 
 	{ event AE_CL_PLAYSOUND 3 "wpn_softball_reload_start_mech_fr05_1p" } 
        eject
	{ event AE_CL_PLAYSOUND 8 "SG_Twin_B.Reload_Eject" } 
	{ event AE_CL_PLAYSOUND 0 "Weapon_Sidewinder_Reload_1_1P" } 
	load shell
	{ event AE_CL_PLAYSOUND 20 "SG_Twin_B.Reload_InsertMag" } 
	{ event AE_CL_PLAYSOUND 8 "Weapon_Mastiff_Reload_LoadShell" } 
	close
	{ event AE_CL_PLAYSOUND 19 "SG_Twin_B.Reload_Close" }
	{ event AE_CL_PLAYSOUND 28 "Weapon_RE45_Reload_MagInsert" } 
	draw
	{ event AE_CL_PLAYSOUND 0 "SG_twinB.Draw" }
	{ event AE_CL_PLAYSOUND 0 "Weapon_R101_Equip" } 
	holster
	{ event AE_CL_PLAYSOUND 0 "SG_twinB.Holster" }
	{ event AE_CL_PLAYSOUND 0 "Weapon_R101_UnEquip" } 
```
blender_kjX6TDLkRd

### CODE REVIEW

**Comment by GeckoEidechse** [comment]
@EM4Volts

**Comment by EM4Volts** [comment]
Looks fine ingame, didnt realize there were actual sound events for the db ingame, even fitting the reload perfectly. Guess respawn had the model done and just gave it to nexon then :/

But yeah pr is fine lovin the pbr :)

**Review by EM4Volts — APPROVED** [review]
Tested locally, (as said before, but didnt realize where the review button is) 

Works. Xoxo

**Review by GeckoEidechse — APPROVED** [review]
Signing off based on previous review done by @EM4Volts who added the twin-barrel shotgun initially

**Comment by GeckoEidechse** [comment]
Putting this in the next feature release, consider this essentially merged :P

**Pull request merged**
