### PR TITLE
chore: French translations

### PR DESCRIPTION
**Pull request by Alystrasz**
Adding French translations to Northstar client.

### CODE REVIEW

**Comment by Alystrasz** [comment]
I fully translated `Northstar.Custom/mod/resource/northstar_custom_french.txt` file, but afterwards I saw a warning message in `Northstar.Client/mod/resource/northstar_client_localisation_english.txt`: https://github.com/R2Northstar/NorthstarMods/blob/aafffda44116b7ac7911dc65826e391c61b458cd/Northstar.Client/mod/resource/northstar_client_localisation_english.txt#L75

@BobTheBob9 should I translate only client file (and not custom one)?

**Comment by BobTheBob9** [comment]
better to translate client, all localisation is in that at the moment

**Review by timoreo22 — APPROVED** [review]
Looks all good to me

**Comment by Alystrasz** [comment]
I'll translate client and switch this as ready for review when I'm done :)

**Comment by BobTheBob9** [comment]
sick, appreciate it

**Review by Alystrasz — COMMENTED** [review]
I added all translations now, please review again.

**Comment by Alystrasz** [comment]
@timoreo22 seems like I can't re-ask for your review, so sorry for the tag I suppose 😄

**Review by timoreo22 — APPROVED** [review]
It's still all good to me :)

**Pull request merged**
