### PR TITLE
Check if server full before connecting

### PR DESCRIPTION
**Pull request by F1F7Y**
Checks if server is full before trying to connect. If it is full doesn't go back to main menu.

### CODE REVIEW

**Review by abarichello — APPROVED** [review]
Thanks! Really useful. Can you fix conflicts so I can merge?

**Comment by F1F7Y** [comment]
image
I fucked the conflicts gimme a sec

**Comment by F1F7Y** [comment]
image
I literally added something; am confused

**Comment by barnabwhy** [comment]
> image
> I literally added something; am confused

is the encoding still utf-16-le? the file has the same contents but is 18kB smaller

**Comment by BobTheBob9** [comment]
i think it might be better to just have this be done on gameserver auth or masterserver, since local playercount will often not be up to date

**Pull request closed without merging**
