### PR TITLE
Add functionality to PlayerAssist callback

### PR DESCRIPTION
**Pull request by NoCatt**
Adds a function to the player killed callback that is just a copy paste of how we handle assists everywhere else 

yes this PR is untested :>

### CODE REVIEW

**Comment by ASpoonPlaysGames** [comment]
Very weird whitespace stuff going on here lol

Will properly review once I can tell what actually changed

**Comment by Zanieon** [comment]
Any updates on this to solve conflicts? There's some other stuff that requires changing as well before merging.

**Comment by GeckoEidechse** [comment]
merge conflicts still

**Comment by GeckoEidechse** [comment]
Aight, I reverted all the unrelated whitespace changes via f824608f742ddfb08fa430f5ab32c2be89798bd7

(omfg we desperately need a Squirrel formatter so this doesn't keep happening and doesn't need to be done by hand...)

**Comment by Zanieon** [comment]
Closing this as NoCatt basically dropped all activity for Northstar, halting this PR, which also got superseded by #908

**Pull request closed without merging**
