### PR TITLE
Traditional Chinese translation

### PR DESCRIPTION
**Pull request by zestybaby**
As a native speaker of Simplified Chinese there has to be a lot of mistakes and misuse of words in this translation, but in the current version of this PR it's perfect for Simplified Chinese speakers to understand.

Feel free to contribute actual Trad. Chinese translation over this one.

### CODE REVIEW

**Comment by x3Karma** [comment]
Should update this with the new better server browser localisation

**Comment by zestybaby** [comment]
Updated with the merged server browser build.

**Comment by abarichello** [comment]
Have you tested this successfully in-game? For some reason portuguese, german and tradicional chinese are defaulting to english translations.

**Comment by x1123581321** [comment]
請問如何更改語言，貌似我用了不行

**Comment by wolf109909** [comment]
遊戲安裝繁體中文試試

**Comment by x1123581321** [comment]
> 遊戲安裝繁體中文試試

欸豆，痾，我是裝繁體的欸，還是是我安裝問題?

**Comment by Orpheus2401** [comment]
> Have you tested this successfully in-game? For some reason portuguese, german and tradicional chinese are defaulting to english translations.

It seems to be encoding format problem, these localization files all using UTF-8 instead of UTF-16 LE

**Comment by wolf109909** [comment]
> 

weird, northstarcn repo uses utf-8 and it works fine

**Comment by abarichello** [comment]
> > Have you tested this successfully in-game? For some reason portuguese, german and tradicional chinese are defaulting to english translations.
> 
> It seems to be encoding format problem, these localization files all using UTF-8 instead of UTF-16 LE
You're right, I got portuguese and german working by converting to UTF-16 LE. I'll convert the rest and add this notice to the wiki. Thanks.

**Comment by abarichello** [comment]
@zestybaby can you reencode this file so I can merge?

**Comment by Juesto** [comment]
tip: check if the git setting core.auto_crlf=true is causing issues (its default on windows and sometimes it can cause issues with some files)

**Comment by zestybaby** [comment]
@abarichello Updated as requested, sorry for the inconvenience.

**Comment by abarichello** [comment]
> @abarichello Updated as requested, sorry for the inconvenience.

No problem, merged through the command line at: https://github.com/R2Northstar/NorthstarMods/commit/0a2978236c1557a08ae41bffa13c81909b2bd106.
Thanks!

**Pull request closed without merging**
