### PR TITLE
Add a doc comment to `StringReplace`

### PR DESCRIPTION
**Pull request by GeckoEidechse**
This is an initial test to get formatting etc agreed upon to then build on this further

Related to #664

### CODE REVIEW

**Comment by GeckoEidechse** [comment]
So looking at this in the diff rn, I think we should drop the `///---------` decorators before/after doc comment cause it just adds more (unnecessary lines).

The [Discord vote a while back](https://discord.com/channels/920776187884732556/922954389415686185/1100154470886809630) was also slightly in favour of a format that doesn't have the decorators though our conclusion back when the vote was done was to combine the two most voted versions

**Comment by ASpoonPlaysGames** [comment]
Ok so, yeah drop the decorators.

But also, do we actually need doc comments for squirrel functions? Squirrel is scripting, mostly not stuff that is reused

**Comment by GeckoEidechse** [comment]
> Ok so, yeah drop the decorators.

Done with c3eba087ed7aa4fe5d8d6faa5452989c42815e46

> But also, do we actually need doc comments for squirrel functions? Squirrel is scripting, mostly not stuff that is reused

The reason is to both improve readability and to then be able to auto-generate documentation directly from code ^^

**Comment by F1F7Y** [comment]
> So looking at this in the diff rn, I think we should drop the `///---------` decorators before/after doc comment cause it just adds more (unnecessary lines).

The entire point of the separators is to add more lines to make it visually easier to separate the comment from code, not all of us have syntax highlighting... I can see how it could get annoying to have to copy paste these and they dont add anything to the docs so whatever the hivemind wants we go with

**Comment by GeckoEidechse** [comment]
> The entire point of the separators is to add more lines to make it visually easier to separate the comment from code, not all of us have syntax highlighting...

Regarding syntax highlighting, we might wanna do a poll on dev setups people use to see what we should target. I'm pretty sure vscode is the highest (and that one has an extension for squirrel). Curious what is second. Probably Notepad++ but not sure if that has any highlighting for Squirrel.

(sidenote: the occasional lack of Syntax highlighting is also why I have a disliking for `/* ... */` style comments :P)

>  I can see how it could get annoying to have to copy paste these and they dont add anything to the docs so whatever the hivemind wants we go with

For me it's mostly the visual clutter they add. I think the easiest solution is to just do a poll on what people prefer and go with that. Imma set one up.
In the end regardless of which one we go for, if we ever wanna change adding/removing the decorators should be quite easy.

**Comment by GeckoEidechse** [comment]
Made a poll in #759

**Comment by GeckoEidechse** [comment]
> Made a poll in #759

Poll is currently at 7:2 in favour of no decorators so I'd say we do _no decorators_ for now ^^

**Pull request merged**
