### PR TITLE
Add translation status indicator badge to README

### PR DESCRIPTION
**Pull request by GeckoEidechse**
Adds badge showing current translation status.

Change is only in README so no testing should be necessary (unless with testing you mean looking at rich diff and verifying that it renders, lol)

Rendered:

image

~~Sorta closes https://github.com/R2Northstar/Northstar/issues/343~~

### CODE REVIEW

**Comment by p0358** [comment]
Closes R2Northstar/Northstar#343 (I think)

That is unless one'd want to add full chart like FlightCore has too:
image

**Comment by GeckoEidechse** [comment]
> That is unless one'd want to add full chart like FlightCore has too:

Good point, updated with d6803cb6029173e50189de7290453953d13d2083

**Review by p0358 — APPROVED** [review]

**Review by ASpoonPlaysGames — APPROVED** [review]
Sure, why not

Looks fine to me: 
image

**Comment by GeckoEidechse** [comment]
mfw I forget about a PR that was ready to merge :clueless:

**Pull request merged**
