### PR TITLE
Add custom FD wave names

### PR DESCRIPTION
**Pull request by GeckoEidechse**
Made by @Zanieon, cherry-picked by me out from #671

### CODE REVIEW

**Comment by GeckoEidechse** [comment]
@EM4Volts @F1F7Y if you wanna recheck rq :>

**Review by EM4Volts — COMMENTED** [review]
english looks good, works aswell. still cant speak portuguese tho.

**Review by ASpoonPlaysGames — COMMENTED** [review]
I don't really see the point of this honestly? FD doesn't support those maps yet?

**Comment by Zanieon** [comment]
Point is just future-proof of these maps having FD on them. Currently main FD branch doesn't have the code but once i starting doing the PRs in there, the code i did for the full customizable routes and harvester placement system which makes FD work with any map will be one of them.

**Review by Slipstreamm — CHANGES_REQUESTED** [review]
Can't comment on the exact line because github says it's a binary file but "Not an Usual Neighborhood" should be "Not a Usual Neighborhood"

**Comment by Zanieon** [comment]
Honstely, i'll deal with those custom wave names another time when FD is properly integrated into Northstar itself, for now i'd even suggest to delete this branch, i'll reopen one relating to this when the time comes.

**Comment by GeckoEidechse** [comment]
Closing as suggested by @Zanieon in DMs

**Pull request closed without merging**
