### PR TITLE
Add TGG

### PR DESCRIPTION
**Pull request by VITALISED**
I literally have not had a full playtest yet so I'm just drafting for now

### CODE REVIEW

**Comment by VITALISED** [comment]
Also this does make a slight API change in Northstar.CustomServers should mention. Shouldn't have any noticeable impacts however

**Comment by x3Karma** [comment]
how tf when u upload github display the file changes correctly

**Comment by VITALISED** [comment]
+ratio

**Comment by VITALISED** [comment]
Ok I think this works now, had a good 2 hour playtest

**Comment by VITALISED** [comment]
I should probably note the progression lol:
- railgun
- xo16
- pred gun gaming
- leadwall
- particle accel
- meteor
- 40mm
- quad rocket
- scuffed sword sword core
- eject into a pilot (and respawn as one until someone wins)

**Comment by abarichello** [comment]
While play-testing my game crashed when I got a kill with the leadwall. Also in my opinion the xo16 is easier to get a kill than a railgun, what about moving it to the first weapon slot? At least that's how other gun game modes work (easier to kill -> harder to kill)

**Comment by VITALISED** [comment]
These should be mostly fixed, however I couldn't get the titan passives to go away from loadout stuff so might need to look into that

**Comment by VITALISED** [comment]
There's fucking merge conflicts of course

**Comment by VITALISED** [comment]
Going to add health on kill and an earnmeter for next weapon

**Comment by VITALISED** [comment]
#git goes hard

**Comment by VITALISED** [comment]
If anyone can fix the dumb fucking earn meter rui I will give them several thousand dollars (real), literally last thing I need to fix

**Comment by VITALISED** [comment]
Finally after 42 years this PR is ready for review and playtest, I probably wont be able to make it if there is one but most bugs should be fixed with the guys I played with

**Comment by MiloAkerman** [comment]
haha you have funny merge conflicts

**Pull request closed without merging**
