### PR TITLE
Fixed air accel conflicting with sh_custom_air_accel and also fix res…

### PR DESCRIPTION
**Pull request by x3Karma**
…pawning at end kill replay.

### CODE REVIEW

**Comment by GeckoEidechse** [comment]
The diff shown on Github goes over the entire file. Did file encoding or tabs/spaces change?

**Comment by x3Karma** [comment]
I just uploaded whatever I edited. No idea why.

It's tested live in my server though, so there shouldn't be any issues.

**Comment by x3Karma** [comment]
Probably because the file changed doesn't show you anything, I'm just going to detail what I edited.

I moved `player.kv.airAcceleration` from line 116 
image
to thread a function that adds a `WaitFrame()` before applying the air acceleration.
image


I also added prevented respawning during end of kill replay by adding this function.
image

**Comment by connieprice** [comment]
Personally, the diffs on this commit should've really been cleaned up before merging.

**Comment by abarichello** [comment]
I could review what he added by disabling whitespace changes on the web interface, I plan to add code style tools to the repositories in the future

**Comment by connieprice** [comment]
I'm being a bit pedantic, I'm just a sucker for clean diffs.

**Pull request merged**
