### PR TITLE
Fastball: bt do be in a wall on complex

### PR DESCRIPTION
**Pull request by Coopyy**
😳

### CODE REVIEW

**Comment by xamionex** [comment]
image

**Comment by MiloAkerman** [comment]
Please do not merge as BT likes being in walls.

**Comment by GeckoEidechse** [comment]
Please attach screenshots / video recordings of the before and after positions.

Also AFAIK the original BT location on Complex was chosen so that pilots would get thrown directly into the building entrance without hitting a wall or something. With the new positions is it still possible to maintain the speed from the original throw?

**Comment by Coopyy** [comment]
https://media.discordapp.net/attachments/937892759002574869/939580030881759262/XN32klCQ7o.mp4

**Comment by Coopyy** [comment]
before it just kinda threw you into that wall but not over it

**Comment by xamionex** [comment]
> before it just kinda threw you into that wall but not over it

## kill me

**ah~ bt~ be gentle~**

**Comment by GeckoEidechse** [comment]
> before it just kinda threw you into that wall but not over it

I think you had to aim a bit to the left and make you didn't hold jump. So I agreed that updating BT spawns would be nice. The issue I see with the suggestion, is that it would also require rebalancing panel locations, as the new spawn gives that team easier access to both A and B. It was already a bit skewed but this makes it more unbalanced IMO.

Maybe place BT add the edge near the water?

**Comment by Coopyy** [comment]
someone can try that, I just did that for my mode since it was misleading that you could almost make it over that wall

**Pull request closed without merging**
