### PR TITLE
Fix "Kills by Auto-Titan" not registering at all

### PR DESCRIPTION
**Pull request by Zanieon**
This is a quick fix that will redirect the attacker entity to a proper NPC owned by the player.

By default behavior of the game, attackers are always the final entity in the owning hiearchy, which is always a player if owned NPCs kills enemies.

This PR properly redirects the code to the correct NPC whenever they have an owning player.

### CODE REVIEW

**Review by ASpoonPlaysGames — APPROVED** [review]
Code looks good, discussed in discord mostly. Havent tested

**Comment by GeckoEidechse** [comment]
I guess for testing just get another player and have them be killed by auto-titan?

**Comment by Zanieon** [comment]
Tested in my own server by hosting Attrition and FD, so far no crashes in regards to this, and my titan started registering its kills in my profile:
image

**Comment by GeckoEidechse** [comment]
Good enough for me ^^

**Pull request merged**
