### PR TITLE
[FW] Fix Reversed Titan Spawnpoint on Boomtown

### PR DESCRIPTION
**Pull request by DBmaoha**
Respawn left a reversed titan start point on Boomtown( mp_grave ), which will make fw's "Respawn as Titan" have a wrong start point

### CODE REVIEW

**Review by GeckoEidechse — APPROVED** [review]
Confirmed working in testing.

Tested in 1-player listen server, 2 rounds of Frontier War on Boomtown, one with PR one without. Without PR respawn with Titan on wrong side, with PR correct side.

Also tested 1 round on Forwardbase Kodai just to be sure the PR doesn't break anything by accident :P

**Comment by DBmaoha** [comment]
> Would it be potentially better to simply edit the .ent files (through keyvalues or something) to fix the bad spawns?

the spawn points are decided for ttdm or some other respawn as titan conditions, they're never considered about fw I guess, so my way to fix it is add a hack in _gamemode_fw. also changing fw related spawnpoints will cause minimap territory issues, which related in .bsp file iirc( https://github.com/R2Northstar/NorthstarMods/issues/573 )

**Comment by F1F7Y** [comment]
> Also changing fw related spawnpoints will cause minimap territory issues
The minimap territory image is in an rpak, the actuall territory volume is defined using triggers in the `.bsp` so this is false

**Review by F1F7Y — APPROVED** [review]
Works in testing, code looks good

**Review by uniboi — APPROVED** [review]
Kind of a workaround but it's fine. Code looks good, there isn't a lot to review really

**Pull request merged**
