### PR TITLE
Add Fastball locations for Homestead and Drydock

### PR DESCRIPTION
**Pull request by GeckoEidechse**
Some locations are still subject to tweaks, especially Drydock B panel

### CODE REVIEW

**Comment by GeckoEidechse** [comment]
Panel locations on Homestead

mp_homestead0042
mp_homestead0040
mp_homestead0041

**Comment by GeckoEidechse** [comment]
Panel locations on Drydock (note that _B_ will likely be moved next to the ship instead of on top):
mp_drydock0003
mp_drydock0002
mp_drydock0000

**Comment by GeckoEidechse** [comment]
Dragging @Neoministein into this as well to take a look as they made the panels for _Forwardbase Kodai_, _Colony_, and _Complex_.

**Comment by Neoministein** [comment]
I'd agree on putting panel B on drydock on the floor next to the ship instead of on the drop ship. Due the panel locations being in semi or full cover. The rest look good to me ^^

**Comment by GeckoEidechse** [comment]
Updated location for B on Drydock based on feedback:

mp_drydock0001

**Comment by GeckoEidechse** [comment]
Alright fuck, trying to rebase just made things worse haha

Imma go full [xkcd 1597](https://xkcd.com/1597/) and make a new merge request ^^

**Comment by GeckoEidechse** [comment]
Check #95 for new PR

**Pull request closed without merging**
