### PR TITLE
Fix weapon drop callback breaking SP

### PR DESCRIPTION
**Pull request by itscynxx**
The functions for both weapon drop callbacks are in an `#if MP` statement, but the globalization wasn't, causing SP to try to add the functions, which it didn't find as MP wasn't active. Without this change, you compile error before SP finishes loading

Sidenote: genuinely wtf is that last line diff. I didn't touch it??
sideline 2: ok i did actually touch it now but it still shows the exact same thing even after removing the newline, idk man

Related:
- #692

### CODE REVIEW

**Review by uniboi — COMMENTED** [review]
Is there a reason the callbacks aren't defined for both SP and MP?

**Comment by GeckoEidechse** [comment]
> Is there a reason the callbacks aren't defined for both SP and MP?

Probably not, cc @NoCatt to be sure ig
c.f.: #692

**Comment by itscynxx** [comment]
> Is there a reason the callbacks aren't defined for both SP and MP?

I can't be 100% sure as it's not my code, but looking at the original pr it's used in MP to destroy weapon drops if they aren't allowed, instead of the solution which apparently didn't always work before

More than willing to edit this to work for SP also, but I was just concerned on making the game not crash

**Comment by GeckoEidechse** [comment]
bump

**Comment by itscynxx** [comment]
> bump

I haven't made any changes due to not having a reply on editing the code to instead work on SP

I suppose the main question would be do we want to move the functions to be above the `#if MP` they're currently inside of, or to end the `#if MP` before the functions (as presumably the functions above are vanilla/replicating vanilla? so we would keep modded functions separate)

**Comment by Zanieon** [comment]
Moving those functions inside the `#if MP` is alright because campaign has its own call of those functions in `_base_gametype_sp.gnut` script which is loaded only in SP.

**Review by Zanieon — APPROVED** [review]

**Comment by Bobbyperson12** [comment]
can confirm that this works completely fine on singleplayer, played through most of a mission, executed a grunt, no issues at all

**Pull request merged**
