### PR TITLE
Add Gamemode: Sticks & Stones

### PR DESCRIPTION
**Pull request by Coopyy**
Based on the popular Call of Duty: Black Ops party mode: Sticks and Stones

full description of the mode can be found here in the northstar discord: https://discord.com/channels/920776187884732556/924283345158959157/927335463436582992

as well as a showcase video made by Iniquity: https://www.youtube.com/watch?v=e8hJIsERpY4

I feel the mode has been popular enough on multiple servers for it to warrant its addition
(also fixed a one in the chamber value on the side :] )

### CODE REVIEW

**Comment by WhiteKnight3098** [comment]
Yes please. I would also request that the configuration system remains intact.

**Comment by itsthehawke** [comment]
Definitely needs to be added, people are going crazy over this, server is always full.

**Comment by DerpedCrusader** [comment]
Been playing this off and on with people, really seems to always be a hit

**Comment by abarichello** [comment]
Thanks for the gamemode! Please remember to keep indentation consistent next contribution

**Comment by Coopyy** [comment]
Thank you! sorry about that, seems to break things depending on which editor I use

**Pull request merged**
