### PR TITLE
Add server browser filter

### PR DESCRIPTION
**Pull request by KanjiuAkuma**
Client mod changes required for server browser filter.
Adds a simple search box to the server browser to search for servers.

Launcher PR: https://github.com/R2Northstar/NorthstarLauncher/pull/16

Example:
image

### CODE REVIEW

**Comment by birdsnestt** [comment]
This is already a feature of the better serverbrowser mod

**Comment by KanjiuAkuma** [comment]
Ah, well, I see, should I just close the PRs then?

**Comment by BLPFBisa** [comment]
I'd rather say the focus should be shifted to including better serverbrowser in the core mod

**Comment by KanjiuAkuma** [comment]
Sure, we can use this as base. Plan was to add things like ping, playlist, ... later anyways so its implemented in a way that makes it easy to add filters

**Comment by Alystrasz** [comment]
I think what @BLPFBisa meant by "shifting the focus" is "improve the already-existing solution instead of recreating another one" :)

https://github.com/F1F7Y/Better.Serverbrowser

**Comment by BobTheBob9** [comment]
the current plan is to merge betterserverbrowser when it's stable enough

**Comment by KanjiuAkuma** [comment]
I see. I'll close the PRs then and take a look at the mod itself and see if I can help out there :)

**Pull request closed without merging**
