### PR TITLE
fix: Multiple mod versions

### PR DESCRIPTION
**Pull request by Alystrasz**
For a detailed description, see launcher PR: https://github.com/R2Northstar/NorthstarLauncher/pull/758

# Testing (`RequiredOnClient` mod version enabling)

##### Core mods

Launch game and join any server:
<details>
<summary>with `Northstar.Client` local version not matching server version (connection should be allowed);</summary>

```text
Nothing special should appear in your logs here.
```

</details>
<details>
<summary>with `Northstar.Client` disabled (mod should be enabled before connection).</summary>

```text
[2024-08-31] [00:33:18] [NORTHSTAR] [info] Attempting authentication with server of id "2fae3133f3822d55461631b86bc7de45"
[2024-08-31] [00:33:19] [SCRIPT UI] [info] Enabled "Northstar.Custom" (v1.19.0) to join server.
```

</details>

##### Gamemode mods

Install several versions of a same mod ([Parkour](https://thunderstore.io/c/northstar/p/Alystrasz/Parkour/) `v0.2.0` + `v0.2.1` for instance) then:

<details>
<summary>Enable/disable any version in any order through the mods menu (should work fine);</summary>

[multiple_versions_handling.webm](https://github.com/user-attachments/assets/2d1bdf42-8460-42cb-8a5c-7e3e4c593c4e)
</details>

<details>
<summary>Disable both versions and join a Parkour server (mod with matching version should be enabled);</summary>

```text
[2024-08-31] [00:39:33] [NORTHSTAR] [info] 'Parkour' loaded successfully, version 0.1.2 (DISABLED)
[...]
[2024-08-31] [00:39:33] [NORTHSTAR] [info] 'Parkour' loaded successfully, version 0.2.1 (DISABLED)
[...]

[2024-08-31] [00:39:43] [NORTHSTAR] [info] Requesting server list from https://northstar.tf
[2024-08-31] [00:39:43] [NORTHSTAR] [info] Got 86 servers
[2024-08-31] [00:39:47] [NORTHSTAR] [info] Attempting authentication with server of id "ff7235e0108a4fb51d278642e9e9b800"
[2024-08-31] [00:39:48] [SCRIPT UI] [info] "Northstar.Custom" (v1.19.0) is required and already enabled.
[2024-08-31] [00:39:48] [SCRIPT UI] [info] Enabled "Parkour" (v0.2.1) to join server.
[...]

[2024-08-31] [00:39:48] [NORTHSTAR] [info] 'Parkour' loaded successfully, version 0.1.2 (DISABLED)
[...]
[2024-08-31] [00:39:48] [NORTHSTAR] [info] 'Parkour' loaded successfully, version 0.2.1
```

</details>

<details>
<summary>Note the server-exposed version, disable it locally and enable the other one, then join the server (current version should be disabled and the other one enabled).</summary>

```text
[2024-08-31] [00:42:58] [NORTHSTAR] [info] 'Parkour' loaded successfully, version 0.1.2
[...]
[2024-08-31] [00:42:58] [NORTHSTAR] [info] 'Parkour' loaded successfully, version 0.2.1 (DISABLED)
[...]

[2024-08-31] [00:43:26] [NORTHSTAR] [info] Attempting authentication with server of id "ff7235e0108a4fb51d278642e9e9b800"
[2024-08-31] [00:43:27] [SCRIPT UI] [info] "Northstar.Custom" (v1.19.0) is required and already enabled.
[2024-08-31] [00:43:27] [SCRIPT UI] [info] Disabled "Parkour" (v0.1.2) since it's not required on server.
[2024-08-31] [00:43:27] [SCRIPT UI] [info] Enabled "Parkour" (v0.2.1) to join server.
[...]

[2024-08-31] [00:43:27] [NORTHSTAR] [info] 'Parkour' loaded successfully, version 0.1.2 (DISABLED)
[...]
[2024-08-31] [00:43:27] [NORTHSTAR] [info] 'Parkour' loaded successfully, version 0.2.1
```
</details>

(ask @Alystrasz if Parkour server is not up)

### CODE REVIEW

**Comment by GeckoEidechse** [comment]
Just in case you weren't aware for compile check to pass, you'll need to add `NSIsModRequiredOnClientWithVersion` to `.github/nativefuncs.json` ^^

**Comment by Alystrasz** [comment]
> Just in case you weren't aware for compile check to pass, you'll need to add `NSIsModRequiredOnClientWithVersion` to `.github/nativefuncs.json` ^^

I am aware, but I'll do that in the end, since I plan to do some additional refactoring of the launcher API 😄

**Comment by GeckoEidechse** [comment]
Heads-up there's merge conflicts atm

**Comment by GeckoEidechse** [comment]
> I don't think so, the label was added by the bot last week but hasn't been removed since then

Yup, you're right. No clue why bot didn't auto-remove the label again, I'll investigate o7

**Comment by Alystrasz** [comment]
https://github.com/R2Northstar/NorthstarMods/pull/899 has been merged, but some (previously removed) functions were added back during the process (e.g. `NSIsModRequiredOnClient`).
Moving this to draft while I fix the issue.

**Comment by Alystrasz** [comment]
Superceded by https://github.com/R2Northstar/NorthstarMods/pull/903.

**Pull request closed without merging**
