### PR TITLE
Localize stringcommands to allow servers to use localised messages

### PR DESCRIPTION
**Pull request by ASpoonPlaysGames**
allows for cool localised messages, including ui images within the messages
image
image
image

### CODE REVIEW

**Comment by uniboi** [comment]
where test mod

**Comment by NoCatt** [comment]
one of the single greatest PRs to ever exist

**Comment by ASpoonPlaysGames** [comment]
> where test mod

havent made yet

**Comment by ASpoonPlaysGames** [comment]
also doesnt rly need a test mod per say, a command is enough

**Comment by ASpoonPlaysGames** [comment]
`script NSSendAnnouncementMessageToPlayer(player, "%%$rui/pilot_loadout/mods/gunrunner%% %%$r2_ui/menus/loadout_icons/attachments/suppressor%% %%$r2_ui/menus/loadout_icons/primary_weapon/primary_kraber%%", "death", <255, 0, 0>, 1, 0)`

should work

**Review by catornot — APPROVED** [review]
amazing

**Comment by uniboi** [comment]
image
code looks good and works in testing

**Review by uniboi — APPROVED** [review]
image
code looks good and works in testing

**Review by GeckoEidechse — APPROVED** [review]
Works in testing using  `script NSSendAnnouncementMessageToPlayer(GetPlayerArray()[0], "%%$rui/pilot_loadout/mods/gunrunner%% %%$r2_ui/menus/loadout_icons/attachments/suppressor%% %%$r2_ui/menus/loadout_icons/primary_weapon/primary_kraber%%", "death", <255, 0, 0>, 1, 0)`

image

**Pull request merged**
