### PR TITLE
Fix serverbrowser filtering by gamemode

### LINKED ISSUE #638: Filtering server browser by gamemode is broken
Likely caused by #623 as it's the only recent PR that changed serverbrowser code that I can see

### PR DESCRIPTION
**Pull request by ASpoonPlaysGames**
Closes #638

### CODE REVIEW

**Comment by ASpoonPlaysGames** [comment]
Requesting review (and hopefully merge) from fifty because I believe gecko is rather busy this week

**Review by uniboi — APPROVED** [review]
Yep code looks good. it's just an oversight from the structs

**Comment by F1F7Y** [comment]
> (and hopefully merge)

Even if i were to merge it rn gecko is the one making releases and deciding what goes into them

**Review by GeckoEidechse — APPROVED** [review]
Confirmed working in testing

**Pull request merged**
