### PR TITLE
Server name in Scoreboard Panel

### PR DESCRIPTION
**Pull request by H0L0theBard**
Adds the server name to the scoreboard replacing the gamemode description 
image

Additionally, this works fine with larger server names 
image

### CODE REVIEW

**Comment by H0L0theBard** [comment]
Just leaving this as a draft if anyone has any suggestions to improve it

**Comment by GeckoEidechse** [comment]
Closes https://github.com/R2Northstar/Northstar/issues/271

**Comment by GeckoEidechse** [comment]
fa127aea89b048825bfd55b78b80fd7a9243f1ae is just the vanilla dump Squirrel scripts, right? ^^

**Comment by H0L0theBard** [comment]
Yeah but with 
`RuiSetString( Hud_GetRui( file.header.gametypeDesc ), "desc", GetConVarString( "ns_server_name" ))`
instead of the regular way to set gamemode description

**Comment by x3Karma** [comment]
this seems more useful as a mod though unless you can somehow keep the gamemode description along with the server name.

Maybe make it alternate between the gamemode description, the server name/description somehow?

**Comment by H0L0theBard** [comment]
I'll test out some stuff to see if I can keep the description and have the server name.

**Comment by F1F7Y** [comment]
Isn't `ns_server_name` used for server names ?
Meaning with this if I join a server `ns_server_name` gets updated so it shows the correct server name. After that though if I start a listen server the name will be wrong.

Also if you plan on expanding the amount of information shown using the *MATCH GOALS* panel could be one way to display the info nicely. 
image

**Comment by BobTheBob9** [comment]
you could probably just make ns_server_name FCVAR_REPLICATED so it gets updated on server join, though I'm not sure hiding the gamemode description on scoreboard is something we should do

**Comment by H0L0theBard** [comment]
Yeah that's fair 
Could potentially put this information in the MATCH GOALS panel like Fifty suggested

**Comment by H0L0theBard** [comment]
@F1F7Y regarding `ns_server_name`, it will change back to the value set in the server autoexec when you leave the match. If you proceed to host a listen server after that, it will be correctly set to what is in the autoexec.

**Comment by H0L0theBard** [comment]
I intend to do a rework of this and move the info away from the scoreboard panel so that it preserves the ability to see gamemode description.

**Comment by GeckoEidechse** [comment]
> @GeckoEidechse was this blocked?.

https://github.com/R2Northstar/NorthstarMods/pull/335#issuecomment-1116078600

**Comment by uniboi** [comment]
me when 7 months old pr and still drafted

**Comment by GeckoEidechse** [comment]
(closed in favour of #536)

**Pull request closed without merging**
