### PR TITLE
Added Callsign Event for Core Earned And Titan Kill

### PR DESCRIPTION
**Pull request by DBmaoha**
Event from vanilla

### CODE REVIEW

**Review by x3Karma — APPROVED** [review]

**Comment by x3Karma** [comment]
Dealt with score events stuff before so I'm pretty sure it's all good.

**Review by ASpoonPlaysGames — APPROVED** [review]
Is there any chance you could do the Titan Assist ones as well if they don't already exist?

**Comment by DBmaoha** [comment]
> Is there any chance you could do the Titan Assist ones as well if they don't already exist?

wait I thought northstar don't have the "TitanAssist" score event, I can't make it a callsign event since only specific kinds of score events can choose whether to trigger a callsign event

**Comment by ASpoonPlaysGames** [comment]
> > Is there any chance you could do the Titan Assist ones as well if they don't already exist?
> 
> wait I thought northstar don't have the "TitanAssist" score event, I can't make it a callsign event since only specific kinds of score events can choose whether to trigger a callsign event

If you think that it is beyond the scope of the PR, don't worry about it. With that being said, I don't know if that event exists in northstar. If not, it should be made

**Pull request merged**
