### PR TITLE
Doom Damage Scalar

### PR DESCRIPTION
**Pull request by IzayoiPADSakuya**
Modify the damage taken by enemy while titan was doomed,different difficulties have different scales.

### CODE REVIEW

**Comment by x3Karma** [comment]
You pull requested this to the main branch instead of the FD branch.

> Modify the damage taken by enemy while titan was doomed,different difficulties have different scales.

Never heard of this before.

**Comment by Dinorush** [comment]
I have also never heard of this. I thought the only damage modifier in FD was the flat enemy damage buff.

**Comment by BobTheBob9** [comment]
given that this modifies playlists, it's probably not vanilla behaviour

**Comment by GeckoEidechse** [comment]
> given that this modifies playlists, it's probably not vanilla behaviour

The playlist change reverts #453 so I assume it's just an accidental copy of that file from before that PR got merged.

**Comment by RoyalBlue1** [comment]
I will close this because I don't think this is vanilla behaviour. In case you have proof of this being in vanilla you can post it in here and reopen this pr.

**Comment by IzayoiPADSakuya** [comment]
x1. Damage scaling for the player's titan doomed
2. AI on easy difficulty will not use Defensive Ability (except for Arc Titan)
3. depending on difficulty grunt will use Charge Rifle,hard 2,master 4
4. Depending on difficulty AI hits
5. Combat score/assist score/pulse knife acquisition mechanism
6. AI titan moves too fast
7. Nuketitan don't melee&dash
8. Some units have a fixed number of core values
9. Shield value of collector changes according to difficulty
10. Scaling of damage taken by collectors based on number of people
11. Tactical kills do not work on ai
12. Attacking titan does not give money, a titan fixed 50$
13.Some weapon weakening accessories are not in effect "damage_heavyarmor_nontitan_scale"(epg,Cold War)
14. Depending on the difficulty the Ghost Warrior will deploy a particle shield

Translated with www.DeepL.com/Translator (free version)
x1.玩家的泰坦黄血状态的伤害缩放
2.简单难度下的AI不会使用防御技能（电弧泰坦除外）
3.根据难度步兵会使用电笔
4.根据难度AI命中率
5.战斗分数/辅助分数/脉冲刀 获取机制
6.AI行动过快
7.核武不会近战冲刺
8.部分单位核心值获取数量为固定数值
9.根据难度采集机护盾数值变化
10.根据人数采集机受到的伤害缩放
11.战术击杀对ai不生效
12.攻击泰坦不给钱，一个泰坦固定50$
13.部分武器削弱配件未生效"damage_heavyarmor_nontitan_scale"
14.根据难度幽灵战士会部署粒子盾
15.泰坦值倍率是0.7，只有疯狂是0.5（需要测试）

I am an experienced frontier player and I know a lot of game mechanics that you don't know.
I don't know English sry
我是一个资深的边境玩家，我知道很多你们不知道的游戏机制。
我不懂英文sry





> 我会关闭这个，因为我不认为这是香草行为。如果你有证据证明这是在香草，你可以把它张贴在这里，并重新打开这个pr。

**Comment by ASpoonPlaysGames** [comment]
Some videos of these things happening would be appreciated, so we can try and copy the behaviour better

**Comment by x3Karma** [comment]
They forgot to translate 15. Which is:

> Titan Core Meter gain is 0.7%, on Insane it is 0.5%

**Comment by IzayoiPADSakuya** [comment]
> They forgot to translate 15. Which is:
> 
> > Titan Core Meter gain is 0.7%, on Insane it is 0.5%

Pilot boost meter multiplier,70%,insane is 50%(A test is required to confirm that the values are accurate需要测试确认数值是否准确)

**Comment by ASpoonPlaysGames** [comment]
> A test is required to confirm that the values are accurate

No need to test if the values are accurate, its part of the playlist vars taken from vanilla (and i think already implemented?)

```
fd_easy
		{
			inherit fd
			vars
			{
                name #PL_fd_easy
                lobbytitle #PL_fd_easy_lobby
                description #PL_fd_easy_desc
 				abbreviation #FD_DIFFICULTY_EASY

                image fd_easy
				fd_difficulty 0
				boost_store_team_reserve 1
				fd_titan_health_adjust			-5000
				fd_reaper_health_adjust 		-2000
				fd_mortar_spectre_setup_time	10
				fd_grunt_at_weapon_users		0
				fd_grunt_shield_captains		0
				fd_player_damage_scalar			1.0
				fd_money_per_round				700
				fd_pro_titan_shields			0
				fd_harvester_shield 			6000
				fd_at_unlimited_ammo            1

				earn_meter_pilot_multiplier		0.7
			}
		}
```
```
fd_insane
		{
			inherit fd
			vars
			{
                name #PL_fd_insane
                lobbytitle #PL_fd_insane_lobby
                description #PL_fd_insane_desc
 				abbreviation #FD_DIFFICULTY_INSANE
                image fd_insane
                fd_difficulty 4
				boost_store_team_reserve 1
				riff_minimap_state 1
                roundscorelimit 1

				fd_titan_health_adjust			0
				fd_reaper_health_adjust 		0
				fd_mortar_spectre_setup_time	5
				fd_grunt_at_weapon_users		4
				fd_grunt_shield_captains		1
				fd_player_damage_scalar			2.5
				fd_money_per_round				600
				fd_pro_titan_shields			1
				fd_harvester_shield 			4000
				fd_at_unlimited_ammo            0

				earn_meter_pilot_multiplier	0.5
			}
		}
```

**Comment by IzayoiPADSakuya** [comment]
> > A test is required to confirm that the values are accurate
> 
> No need to test if the values are accurate, its part of the playlist vars taken from vanilla (and i think already implemented?)
> 
> ```
> fd_easy
> 		{
> 			inherit fd
> 			vars
> 			{
>                 name #PL_fd_easy
>                 lobbytitle #PL_fd_easy_lobby
>                 description #PL_fd_easy_desc
>  				abbreviation #FD_DIFFICULTY_EASY
> 
>                 image fd_easy
> 				fd_difficulty 0
> 				boost_store_team_reserve 1
> 				fd_titan_health_adjust			-5000
> 				fd_reaper_health_adjust 		-2000
> 				fd_mortar_spectre_setup_time	10
> 				fd_grunt_at_weapon_users		0
> 				fd_grunt_shield_captains		0
> 				fd_player_damage_scalar			1.0
> 				fd_money_per_round				700
> 				fd_pro_titan_shields			0
> 				fd_harvester_shield 			6000
> 				fd_at_unlimited_ammo            1
> 
> 				earn_meter_pilot_multiplier		0.7
> 			}
> 		}
> ```
> 
> ```
> fd_insane
> 		{
> 			inherit fd
> 			vars
> 			{
>                 name #PL_fd_insane
>                 lobbytitle #PL_fd_insane_lobby
>                 description #PL_fd_insane_desc
>  				abbreviation #FD_DIFFICULTY_INSANE
>                 image fd_insane
>                 fd_difficulty 4
> 				boost_store_team_reserve 1
> 				riff_minimap_state 1
>                 roundscorelimit 1
> 
> 				fd_titan_health_adjust			0
> 				fd_reaper_health_adjust 		0
> 				fd_mortar_spectre_setup_time	5
> 				fd_grunt_at_weapon_users		4
> 				fd_grunt_shield_captains		1
> 				fd_player_damage_scalar			2.5
> 				fd_money_per_round				600
> 				fd_pro_titan_shields			1
> 				fd_harvester_shield 			4000
> 				fd_at_unlimited_ammo            0
> 
> 				earn_meter_pilot_multiplier	0.5
> 			}
> 		}
> ```

and i think already implemented：yes（I didn't notice this was implemented）

**Pull request closed without merging**
