### PR TITLE
Quick-Play system

### PR DESCRIPTION
**Pull request by ASpoonPlaysGames**
This is a WIP feature atm, but will add a button (and hopefully some filters) to the lobby which would just instantly put the user into a server to play on

### CODE REVIEW

**Comment by ASpoonPlaysGames** [comment]
Things still needed:

- [ ] Localisation
- [ ] A way for users to define filters
- [ ] Make the algorithm for picking a server choose empty servers if it has to

**Comment by uniboi** [comment]
Are you planning to continue working on this when regions are getting merged?

**Comment by ASpoonPlaysGames** [comment]
Yeah i'm gonna finish this at some point, i mostly stopped work on it because UI, but it is up there on my todo list

**Comment by ASpoonPlaysGames** [comment]
I'm not gonna work on this for a while at least, just not rly feeling it, so closing this

**Pull request closed without merging**
