### PR TITLE
Add DisconnectClient() server function to disconnect a client with a reason.

### PR DESCRIPTION
**Pull request by Erlite**
This PR aims to add a function to allow servers to disconnect clients with a function, as it seems `ClientCommand(player, "disconnect")` is currently blacklisted for Northstar mods. 

I have also noticed it being blacklisted in `Northstar.Custom`, meaning I had to `thread` the function to get around it. I am unsure if it is actually blacklisted, or a simple bug, which is why I decided to just ask directly. It seems nobody on the Discord server knew for sure so it might be the better choice.

This is an example of the following function call:
```squirrel
string reason = format("[Spyglass] You have been banned due to %i infraction(s). Latest infraction: %s", 
    validInfractions, GetInfractionAsString(lastInfraction));

DisconnectClient(player, reason);
```
image

**Noticeable Issues**
Due to the nature of the workaround, it seems attempting to disconnect a client while they're connecting may sometimes crash their game.

### CODE REVIEW

**Comment by Erlite** [comment]
Another solution would be a way to override the message displayed to the client after they've been kicked or banned, but I don't know where I'd have to look at. 

It'd basically be something like:

```squirrel
Server_KickPlayer(player, "Reason here");
```
Which would display the above screenshot but with "Reason here". Same for Ban.

**Comment by uniboi** [comment]
What happens when the player overrides the file to discard the server command?

**Comment by Erlite** [comment]
They won't get the disconnect request. Which doesn't matter because you'd generally kick/ban the player on the server right after sending them a `disconnect` command. 

It would be better to create a way to handle this in native, but for now, this is more of a bandaid fix for the inability to disconnect a client with a reason.

**Comment by uniboi** [comment]
Shouldn't that be in the disconnectClient function?

**Comment by Erlite** [comment]
Fair point actually, I'll get that in.

**Comment by Erlite** [comment]
Will be moved to native with better flexibility.

**Pull request closed without merging**
