### PR TITLE
Make arrow nav wrap around again

### PR DESCRIPTION
**Pull request by KanjiuAkuma**
Arrow nav now jumps to filter panel again if up arrow is pressed and topmost server is selected

### CODE REVIEW

**Comment by F1F7Y** [comment]
I changed this so that you can sort using arrow keys and enter by being able to navigate to the column buttons

**Comment by KanjiuAkuma** [comment]
Makes sense. Made it so it wraps from the title bar to clear and vice versa.

**Comment by F1F7Y** [comment]
Tbh this is a small QoL change that should get merged if the conficts are resolved

**Comment by KanjiuAkuma** [comment]
Resolved the merge conflicts. Had to redo the whole thing, so I opened a new PR (#109 ).

**Pull request closed without merging**
