### PR TITLE
Fixed Multiple Amped Weapons Timers

### PR DESCRIPTION
**Pull request by GalacticMoblin**
Applies the missing signal from the code for the Amped Weapons timer.

(Using another amped weapons boost before the last one ends would make the effect end prematurely when the original timer ended, this PR fixes that)

(if I broke any other changes, whoops)

### CODE REVIEW

**Review by uniboi — APPROVED** [review]
code is looking good, can't test rn

**Comment by BobTheBob9** [comment]
will merge once conflicts are solved

**Comment by uniboi** [comment]
changes from this pr have already been merged.

**Comment by GalacticMoblin** [comment]
I fixed this PR to do what I said it should do

**Review by uniboi — APPROVED** [review]
code still looks good

**Comment by GalacticMoblin** [comment]
Before and after
https://user-images.githubusercontent.com/100473309/206866114-52e58d11-17fb-4064-9fa9-1d4154e89710.mp4

**Comment by GeckoEidechse** [comment]
@BobTheBob9 merge conflicts have been resolved :>

**Review by BobTheBob9 — APPROVED** [review]

**Pull request merged**
