### PR TITLE
Pilots Vs Boss

### PR DESCRIPTION
**Pull request by xamionex**
A Random Pilot is chosen to be the Boss. Others have to fight against them, On the other team another player is chosen to be the Amped which has more HP and has an infinite Stim

### CODE REVIEW

**Comment by xamionex** [comment]
sorry for removing so much whitecode but [this is the problem](https://discord.com/channels/920776187884732556/924468488028971059/932678114847363102) (discord chat link)

**Comment by xamionex** [comment]
fixed, I'm the big dumb. Works perfecto

**Comment by xamionex** [comment]
TODO: Fix you are amped

**Comment by xamionex** [comment]
TODO: NERF THE F*** OUT OF RONIN

**Review by abarichello — APPROVED** [review]
Looks good, can you fix the good ol' localisation files conflict?

**Comment by Coopyy** [comment]
while youre at it can you change the Vs to lowercase vs please its annoying me :]

**Comment by xamionex** [comment]
> while youre at it can you change the Vs to lowercase vs please its annoying me :]

will do rn

**Comment by Coopyy** [comment]
you uh deleted the whole localization bossman

**Comment by xamionex** [comment]
What the fuck

**Comment by xamionex** [comment]
how do i undo bru

**Comment by Coopyy** [comment]
idk lmao

**Comment by Coopyy** [comment]
id just take the local file from current repo and add your stuff back

**Comment by VITALISED** [comment]
Has this gamemode been playtested with people publicly or with any contribs?

**Comment by xamionex** [comment]
> Has this gamemode been playtested with people publicly or with any contribs?

publicly up, the server's name is [EU] xamionex - PilotsVsBoss
although it's using hidden right now but everything works

**Comment by xamionex** [comment]
Until people manage to break it i'll never know if it fully works

**Comment by xamionex** [comment]
Needs a way to check if IMC is empty so the match ends if the boss leaves, same when starting match, if there's less than 2 people don't start threads?

**Comment by xamionex** [comment]
day 14 of changes approved but not merged

**Comment by xamionex** [comment]
Totally didn't mean to push Co-op commits into main ;-;

**Comment by abarichello** [comment]
Closing this so we can focus new gamemodes into the upcoming thunderstore support (soon ™️ )

**Pull request closed without merging**
