### PR TITLE
Add server ping to server listings

### PR DESCRIPTION
**Pull request by barnabwhy**
Required for PR [#5](https://github.com/R2Northstar/NorthstarLauncher/pull/5) on NorthstarLauncher

### CODE REVIEW

**Review by MiloAkerman — COMMENTED** [review]
How about changing lines 136-140 to
```
if( NSServerRequiresPassword( serverIndex ) ) {
	SetButtonRuiText( serverButtons[ i ], "[PWD] " + NSGetServerName( serverIndex ) + " | Ping: " + NSGetServerPing( serverIndex) )
} else {
	SetButtonRuiText( serverButtons[ i ], NSGetServerName( serverIndex ) + " | Ping: " + NSGetServerPing( serverIndex ) )
}
```
Or something similar in order to also show the ping without having to click on each server individually? In the future these could also be colored according to the ping and sorted by ping.

I'm still sorta new to GitHub so I'm not sure if I can add a commit to your PR. Sorry.

**Comment by barnabwhy** [comment]
> How about changing lines 136-140 to
> 
> ```
> if( NSServerRequiresPassword( serverIndex ) ) {
> 	SetButtonRuiText( serverButtons[ i ], "[PWD] " + NSGetServerName( serverIndex ) + " | Ping: " + NSGetServerPing( serverIndex) )
> } else {
> 	SetButtonRuiText( serverButtons[ i ], NSGetServerName( serverIndex ) + " | Ping: " + NSGetServerPing( serverIndex ) )
> }
> ```
> 
> Or something similar in order to also show the ping without having to click on each server individually? In the future these could also be colored according to the ping and sorted by ping.
> 
> I'm still sorta new to GitHub so I'm not sure if I can add a commit to your PR. Sorry.

I did have it set up like that however it gets cluttered since most servers don't reply to pings at the moment

**Comment by MiloAkerman** [comment]
What do you mean? Do all the servers show up as ping pending?

**Comment by barnabwhy** [comment]
Able to work with newest code in my fork of NorthstarLauncher, does not implement ping refreshing

**Comment by barnabwhy** [comment]
Realise this shouldn’t be done so far in advance, especially if there’s a potential rewrite of the server browser using res files and stuff.
Besides it’s a pretty easy implementation so it can be redone to suit new code any time realistically

**Pull request closed without merging**
