### PR TITLE
Adding win achievement

### PR DESCRIPTION
**Pull request by catornot**
Adding a winning achievement
```
UnlockAchievement( player, achievements.MP_WIN )
```

### CODE REVIEW

**Review by H0L0theBard — APPROVED** [review]
Seems to be vanilla behaviour to me
Can't test in-game however as I've already unlocked this achievement

**Comment by GeckoEidechse** [comment]
We're talking about the Origin/Steam achievement here, right? ^^

**Comment by catornot** [comment]
yes

**Review by BobTheBob9 — APPROVED** [review]
```
void function ScriptCallback_UnlockAchievement( int achievementID )
{
        Assert( achievementID > 0 && achievementID < achievements.MAX_ACHIVEMENTS, "Tried to unlock achievement with invalid enum value" )

        #if DEV
                string ref
                foreach( string _ref, int val in achievements )
                {
                        if ( val != achievementID )
                                continue
                        ref = _ref
                        break
                }
                printt( "#############################################" )
                printt( "UNLOCKED ACHIEVEMENT:", ref, "(" + achievementID + ")" )
                printt( "#############################################" )
        #endif //DEV

        if ( Script_IsRunningTrialVersion() )
        {
                printt( "Achievements not awarded in trial version" )
                return
        }


        Plat_UnlockAchievementByID( achievementID )
}
```
doesn't seem to be any side effects to calling this, so don't see any issues here

**Pull request merged**
