### PR TITLE
Check player if is wallruning/wallhanging/hanging something

### PR DESCRIPTION
**Pull request by zxcPandora**
Check player if is wallruning/wallhanging/hanging something

### CODE REVIEW

**Comment by BobTheBob9** [comment]
don't really get the point of this?

**Comment by zxcPandora** [comment]
oh,sorry for my stupid.
Can you explain to me?

**Comment by abarichello** [comment]
Why are you adding this? Doesn't make any sense for me

**Comment by zxcPandora** [comment]
ok,I will close it

**Pull request closed without merging**
