### PR TITLE
Add Fastball spawns for Crash Site and Rise

### PR DESCRIPTION
**Pull request by theroylee**
Created fastball spawns for the following maps:
- Crash Site
- Rise

The only maps that currently don't have any fastball spawns are Drydock, Glitch, Homestead, and Relic. I am planning on completing those as well.

### CODE REVIEW

**Comment by theroylee** [comment]
Here is a brief youtube video showing one of the BT spawns and all of the panel spawns on Rise.

https://www.youtube.com/watch?v=N6l3F8u0NIo

**Comment by theroylee** [comment]
Asking @Neoministein to take a look at these locations to be added.

**Comment by GeckoEidechse** [comment]
Dude, I was working Crash Site but looks like you were faster :P

My B is close to your spot, but a bit lower. The idea being it might provide more cover. I like your B more though ^^
mp_crashsite30000

A and C look fine. I had them further out but for C that keeps crashing me for some reason :c

Generally the approach we had when we made panels in #70 was to put the in spots where there's no direct line of sight from further out places in order to require enemies to push into a spot to prevent hacking (with the exception for Drydock B).

**Comment by GeckoEidechse** [comment]
As for Rise can't say much yet as I haven't tried it myself ^^

**Comment by theroylee** [comment]
> Dude, I was working Crash Site but looks like you were faster :P
> 
> My B is close to your spot, but a bit lower. The idea being it might provide more cover. I like your B more though ^^ mp_crashsite30000
> 
> A and C look fine. I had them further out but for C that keeps crashing me for some reason :c
> 
> Generally the approach we had when we made panels in #70 was to put the in spots where there's no direct line of sight from further out places in order to require enemies to push into a spot to prevent hacking (with the exception for Drydock B).

I like your B spot much better. Do you want to add a commit to change it to your version?

**Comment by GeckoEidechse** [comment]
Sure ^^

**Comment by Neoministein** [comment]
The positions you choose look good in and of itself. However the distance between them may be an issue. The current maps have their panels more closer together and it may be hard to counter a respawn on these distances.

**Comment by theroylee** [comment]
Yeah, that was a worry of my own as well. The maps are larger than most of the other ones. Crash Site has another problem where there are not many places with enough cover to put the panels as they are mostly lane-based maps. with no buildings/cover.

**Comment by theroylee** [comment]
screenshot1
screenshot2
Here are the new locations that I chose to make the panels closer together to make denying respawns more possible.

**Comment by GeckoEidechse** [comment]
> The positions you choose look good in and of itself. However the distance between them may be an issue. The current maps have their panels more closer together and it may be hard to counter a respawn on these distances.

Funnily enough my panels on Crash site were even further apart then @theroylee's. The idea behind it being that as you said it allows for easier respawns which in turn increases the chances of team comebacks and as such makes the game more dynamic. ^^

**Comment by Neoministein** [comment]
> Funnily enough my panels on Crash site were even further apart then @theroylee's. The idea behind it being that as you said it allows for easier respawns which in turn increases the chances of team comebacks and as such makes the game more dynamic. ^^

This could improve the game as you said by making it more dynamic. However I see the possibility with big teams that the game would derive into a stalemate when it's hard to counter a respawn. 

I'd suggest to leave it as it is now and see how it plays out. If crash site turns out to more often then not to lead to a stalemate we can create a new Issue. Or if it turns out that having the panels further apart is better we can maybe change the current maps.

**Comment by BobTheBob9** [comment]
this is ready to merge then? gotta say you've put more thought into these panels than i put into half of the ones i added lmao

**Comment by GeckoEidechse** [comment]
> this is ready to merge then? gotta say you've put more thought into these panels than i put into half of the ones i added lmao

Ngl, Eden and Black Water Canal are really really good :D
But yeah PR looks good to me ^^

(Don't forget about #70 ;P)

**Comment by theroylee** [comment]
> this is ready to merge then? gotta say you've put more thought into these panels than i put into half of the ones i added lmao

Yep! This is all ready to merge!

**Pull request merged**
