### PR TITLE
Add URI Handlers

### PR DESCRIPTION
**Pull request by emma-miler**

### CODE REVIEW

**Comment by GeckoEidechse** [comment]
Requires https://github.com/R2Northstar/NorthstarLauncher/pull/75

**Comment by GeckoEidechse** [comment]
One issue with this is that when opening a `northstar://` URI link on main menu or with Northstar closed, the player will be pushed directly into a game bypassing the `communities_hostname` fix.

**Comment by GeckoEidechse** [comment]
#214 should fix that

**Comment by emma-miler** [comment]
- [ ] Add button to generate invite to the in-game escape menu

**Pull request closed without merging**
