### PR TITLE
new Amped Hardpoint Logic

### PR DESCRIPTION
**Pull request by RoyalBlue1**
Logic in line with base game
neither #7 nor #42 are addressed but I will address #7 next
Game logic is implemented according to this video https://www.youtube.com/watch?v=wuUXh_sxkUM

### CODE REVIEW

**Comment by RoyalBlue1** [comment]
I just realized there is still a Problem in the scoring. Points are still awarded when the hardpoint is contested.
I already wrote a fix for that but I cant playtest it right now

**Comment by pg9182** [comment]
Also, capping/amping should happen faster if there's more than one friendly on it (I don't remember the exact amount, though).

**Comment by RoyalBlue1** [comment]
Yes its already implemented in here. From what I got from timing with a stopwatch on videos its a flat multiplier in progress. And in the video I linked it said it maxed at 4
So amping takes 30 seconds alone 15 with 2 players and 10 with 3 players.

**Comment by pg9182** [comment]
Ah, I see it now: https://github.com/R2Northstar/NorthstarMods/pull/106/files#diff-b23db1c782b0fc75087110070843f75f727596e423bd132ea88ecde1496554b4R279; I missed it in my first skim.

**Comment by BobTheBob9** [comment]
has this been tested at all? i'm down to merge when i can confirm this is ready

**Comment by abarichello** [comment]
Testing it this exact moment

**Comment by abarichello** [comment]
Ok, I added some improvements to this PR. I tested a lot of the interactions, amped hardpoint is full of corner cases but I believe this should be enough to have a decent game. Too bad it's not that popular to playtest with a large group.

**Comment by abarichello** [comment]
Btw, we are also missing the animation that plays when the capture point stage changes: https://youtu.be/wuUXh_sxkUM?t=87

**Comment by pg9182** [comment]
> Too bad it's not that popular to playtest with a large group.

I can do that tonight if other people are interested.

**Comment by abarichello** [comment]
https://user-images.githubusercontent.com/16687318/149697681-82636b21-05e7-419c-b17a-f9d59d8bf8f4.mp4

Not sure what you are talking about, your cenario works fine on master branch

**Pull request merged**
