### PR TITLE
Fix attempt to cast null to int in sh_loadouts.nut

### PR DESCRIPTION
**Pull request by Erlite**
image

### CODE REVIEW

**Comment by uniboi** [comment]
when does this happen?

**Comment by BobTheBob9** [comment]
does other code deal fine with this func returning -1?

**Comment by F1F7Y** [comment]
Erlite forgor :skull:

**Comment by F1F7Y** [comment]
Feels kinda weird that value being `null` returns `-1` instead of `0`

**Comment by ASpoonPlaysGames** [comment]
@Erlite is this PR stale?

**Comment by Erlite** [comment]
> when does this happen?
> 

Don't remember

**Comment by Erlite** [comment]
> does other code deal fine with this func returning -1?

Everything else was fine during testing AFAIK

**Comment by Erlite** [comment]
> @Erlite is this PR stale?

Not really, it can still be merged if wanted

**Comment by Zanieon** [comment]
Tempted to close this PR as it is stale, and Erlite never gave much context in regards of what occasions this fix could be needed, on those 2 years that has passed there wasn't any reported problem in regards to this as well.

**Pull request closed without merging**
